// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ChatMessage.proto

package com.road.pb;

public final class ChatMsgProto {
  private ChatMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 channelType = 1;
    boolean hasChannelType();
    int getChannelType();
    
    // optional string sendName = 2;
    boolean hasSendName();
    String getSendName();
    
    // optional int32 recvId = 3;
    boolean hasRecvId();
    int getRecvId();
    
    // repeated int32 recvIdList = 4;
    java.util.List<java.lang.Integer> getRecvIdListList();
    int getRecvIdListCount();
    int getRecvIdList(int index);
    
    // optional string message = 5;
    boolean hasMessage();
    String getMessage();
  }
  public static final class ChatMsg extends
      com.google.protobuf.GeneratedMessage
      implements ChatMsgOrBuilder {
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(Builder builder) {
      super(builder);
    }
    private ChatMsg(boolean noInit) {}
    
    private static final ChatMsg defaultInstance;
    public static ChatMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.road.pb.ChatMsgProto.internal_static_com_road_proto_ChatMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.road.pb.ChatMsgProto.internal_static_com_road_proto_ChatMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 channelType = 1;
    public static final int CHANNELTYPE_FIELD_NUMBER = 1;
    private int channelType_;
    public boolean hasChannelType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getChannelType() {
      return channelType_;
    }
    
    // optional string sendName = 2;
    public static final int SENDNAME_FIELD_NUMBER = 2;
    private java.lang.Object sendName_;
    public boolean hasSendName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSendName() {
      java.lang.Object ref = sendName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sendName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSendNameBytes() {
      java.lang.Object ref = sendName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sendName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 recvId = 3;
    public static final int RECVID_FIELD_NUMBER = 3;
    private int recvId_;
    public boolean hasRecvId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getRecvId() {
      return recvId_;
    }
    
    // repeated int32 recvIdList = 4;
    public static final int RECVIDLIST_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> recvIdList_;
    public java.util.List<java.lang.Integer>
        getRecvIdListList() {
      return recvIdList_;
    }
    public int getRecvIdListCount() {
      return recvIdList_.size();
    }
    public int getRecvIdList(int index) {
      return recvIdList_.get(index);
    }
    
    // optional string message = 5;
    public static final int MESSAGE_FIELD_NUMBER = 5;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      channelType_ = 0;
      sendName_ = "";
      recvId_ = 0;
      recvIdList_ = java.util.Collections.emptyList();;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasChannelType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, channelType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSendNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, recvId_);
      }
      for (int i = 0; i < recvIdList_.size(); i++) {
        output.writeInt32(4, recvIdList_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channelType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSendNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, recvId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < recvIdList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(recvIdList_.get(i));
        }
        size += dataSize;
        size += 1 * getRecvIdListList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.road.pb.ChatMsgProto.ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.pb.ChatMsgProto.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.road.pb.ChatMsgProto.ChatMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.road.pb.ChatMsgProto.ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.road.pb.ChatMsgProto.internal_static_com_road_proto_ChatMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.road.pb.ChatMsgProto.internal_static_com_road_proto_ChatMsg_fieldAccessorTable;
      }
      
      // Construct using com.road.pb.ChatMsgProto.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        channelType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        recvId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        recvIdList_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.road.pb.ChatMsgProto.ChatMsg.getDescriptor();
      }
      
      public com.road.pb.ChatMsgProto.ChatMsg getDefaultInstanceForType() {
        return com.road.pb.ChatMsgProto.ChatMsg.getDefaultInstance();
      }
      
      public com.road.pb.ChatMsgProto.ChatMsg build() {
        com.road.pb.ChatMsgProto.ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.road.pb.ChatMsgProto.ChatMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.road.pb.ChatMsgProto.ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.road.pb.ChatMsgProto.ChatMsg buildPartial() {
        com.road.pb.ChatMsgProto.ChatMsg result = new com.road.pb.ChatMsgProto.ChatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.channelType_ = channelType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendName_ = sendName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.recvId_ = recvId_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          recvIdList_ = java.util.Collections.unmodifiableList(recvIdList_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.recvIdList_ = recvIdList_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.road.pb.ChatMsgProto.ChatMsg) {
          return mergeFrom((com.road.pb.ChatMsgProto.ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.road.pb.ChatMsgProto.ChatMsg other) {
        if (other == com.road.pb.ChatMsgProto.ChatMsg.getDefaultInstance()) return this;
        if (other.hasChannelType()) {
          setChannelType(other.getChannelType());
        }
        if (other.hasSendName()) {
          setSendName(other.getSendName());
        }
        if (other.hasRecvId()) {
          setRecvId(other.getRecvId());
        }
        if (!other.recvIdList_.isEmpty()) {
          if (recvIdList_.isEmpty()) {
            recvIdList_ = other.recvIdList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRecvIdListIsMutable();
            recvIdList_.addAll(other.recvIdList_);
          }
          onChanged();
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasChannelType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              channelType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sendName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              recvId_ = input.readInt32();
              break;
            }
            case 32: {
              ensureRecvIdListIsMutable();
              recvIdList_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addRecvIdList(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 channelType = 1;
      private int channelType_ ;
      public boolean hasChannelType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getChannelType() {
        return channelType_;
      }
      public Builder setChannelType(int value) {
        bitField0_ |= 0x00000001;
        channelType_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannelType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        channelType_ = 0;
        onChanged();
        return this;
      }
      
      // optional string sendName = 2;
      private java.lang.Object sendName_ = "";
      public boolean hasSendName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSendName() {
        java.lang.Object ref = sendName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sendName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSendName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sendName_ = value;
        onChanged();
        return this;
      }
      public Builder clearSendName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendName_ = getDefaultInstance().getSendName();
        onChanged();
        return this;
      }
      void setSendName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        sendName_ = value;
        onChanged();
      }
      
      // optional int32 recvId = 3;
      private int recvId_ ;
      public boolean hasRecvId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getRecvId() {
        return recvId_;
      }
      public Builder setRecvId(int value) {
        bitField0_ |= 0x00000004;
        recvId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRecvId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        recvId_ = 0;
        onChanged();
        return this;
      }
      
      // repeated int32 recvIdList = 4;
      private java.util.List<java.lang.Integer> recvIdList_ = java.util.Collections.emptyList();;
      private void ensureRecvIdListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          recvIdList_ = new java.util.ArrayList<java.lang.Integer>(recvIdList_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<java.lang.Integer>
          getRecvIdListList() {
        return java.util.Collections.unmodifiableList(recvIdList_);
      }
      public int getRecvIdListCount() {
        return recvIdList_.size();
      }
      public int getRecvIdList(int index) {
        return recvIdList_.get(index);
      }
      public Builder setRecvIdList(
          int index, int value) {
        ensureRecvIdListIsMutable();
        recvIdList_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addRecvIdList(int value) {
        ensureRecvIdListIsMutable();
        recvIdList_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllRecvIdList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRecvIdListIsMutable();
        super.addAll(values, recvIdList_);
        onChanged();
        return this;
      }
      public Builder clearRecvIdList() {
        recvIdList_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      
      // optional string message = 5;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        message_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.road.proto.ChatMsg)
    }
    
    static {
      defaultInstance = new ChatMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.road.proto.ChatMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_road_proto_ChatMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_road_proto_ChatMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/ChatMessage.proto\022\016com.road.prot" +
      "o\"e\n\007ChatMsg\022\023\n\013channelType\030\001 \002(\005\022\020\n\010sen" +
      "dName\030\002 \001(\t\022\016\n\006recvId\030\003 \001(\005\022\022\n\nrecvIdLis" +
      "t\030\004 \003(\005\022\017\n\007message\030\005 \001(\tB\033\n\013com.road.pbB" +
      "\014ChatMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_road_proto_ChatMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_road_proto_ChatMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_road_proto_ChatMsg_descriptor,
              new java.lang.String[] { "ChannelType", "SendName", "RecvId", "RecvIdList", "Message", },
              com.road.pb.ChatMsgProto.ChatMsg.class,
              com.road.pb.ChatMsgProto.ChatMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
