// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/PrivateChatMessage.proto

package com.road.pb;

public final class PrivateChatMsgProto {
  private PrivateChatMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PrivateChatMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 sendId = 1;
    boolean hasSendId();
    int getSendId();
    
    // optional int32 recvId = 2;
    boolean hasRecvId();
    int getRecvId();
    
    // optional string message = 3;
    boolean hasMessage();
    String getMessage();
  }
  public static final class PrivateChatMsg extends
      com.google.protobuf.GeneratedMessage
      implements PrivateChatMsgOrBuilder {
    // Use PrivateChatMsg.newBuilder() to construct.
    private PrivateChatMsg(Builder builder) {
      super(builder);
    }
    private PrivateChatMsg(boolean noInit) {}
    
    private static final PrivateChatMsg defaultInstance;
    public static PrivateChatMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public PrivateChatMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.road.pb.PrivateChatMsgProto.internal_static_com_road_proto_PrivateChatMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.road.pb.PrivateChatMsgProto.internal_static_com_road_proto_PrivateChatMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 sendId = 1;
    public static final int SENDID_FIELD_NUMBER = 1;
    private int sendId_;
    public boolean hasSendId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSendId() {
      return sendId_;
    }
    
    // optional int32 recvId = 2;
    public static final int RECVID_FIELD_NUMBER = 2;
    private int recvId_;
    public boolean hasRecvId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getRecvId() {
      return recvId_;
    }
    
    // optional string message = 3;
    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sendId_ = 0;
      recvId_ = 0;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sendId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, recvId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sendId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, recvId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.pb.PrivateChatMsgProto.PrivateChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.road.pb.PrivateChatMsgProto.PrivateChatMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.road.pb.PrivateChatMsgProto.PrivateChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.road.pb.PrivateChatMsgProto.internal_static_com_road_proto_PrivateChatMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.road.pb.PrivateChatMsgProto.internal_static_com_road_proto_PrivateChatMsg_fieldAccessorTable;
      }
      
      // Construct using com.road.pb.PrivateChatMsgProto.PrivateChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sendId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        recvId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.road.pb.PrivateChatMsgProto.PrivateChatMsg.getDescriptor();
      }
      
      public com.road.pb.PrivateChatMsgProto.PrivateChatMsg getDefaultInstanceForType() {
        return com.road.pb.PrivateChatMsgProto.PrivateChatMsg.getDefaultInstance();
      }
      
      public com.road.pb.PrivateChatMsgProto.PrivateChatMsg build() {
        com.road.pb.PrivateChatMsgProto.PrivateChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.road.pb.PrivateChatMsgProto.PrivateChatMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.road.pb.PrivateChatMsgProto.PrivateChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.road.pb.PrivateChatMsgProto.PrivateChatMsg buildPartial() {
        com.road.pb.PrivateChatMsgProto.PrivateChatMsg result = new com.road.pb.PrivateChatMsgProto.PrivateChatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sendId_ = sendId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.recvId_ = recvId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.road.pb.PrivateChatMsgProto.PrivateChatMsg) {
          return mergeFrom((com.road.pb.PrivateChatMsgProto.PrivateChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.road.pb.PrivateChatMsgProto.PrivateChatMsg other) {
        if (other == com.road.pb.PrivateChatMsgProto.PrivateChatMsg.getDefaultInstance()) return this;
        if (other.hasSendId()) {
          setSendId(other.getSendId());
        }
        if (other.hasRecvId()) {
          setRecvId(other.getRecvId());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sendId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              recvId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 sendId = 1;
      private int sendId_ ;
      public boolean hasSendId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSendId() {
        return sendId_;
      }
      public Builder setSendId(int value) {
        bitField0_ |= 0x00000001;
        sendId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSendId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 recvId = 2;
      private int recvId_ ;
      public boolean hasRecvId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getRecvId() {
        return recvId_;
      }
      public Builder setRecvId(int value) {
        bitField0_ |= 0x00000002;
        recvId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRecvId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        recvId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string message = 3;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.road.proto.PrivateChatMsg)
    }
    
    static {
      defaultInstance = new PrivateChatMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.road.proto.PrivateChatMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_road_proto_PrivateChatMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_road_proto_PrivateChatMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036proto/PrivateChatMessage.proto\022\016com.ro" +
      "ad.proto\"A\n\016PrivateChatMsg\022\016\n\006sendId\030\001 \001" +
      "(\005\022\016\n\006recvId\030\002 \001(\005\022\017\n\007message\030\003 \001(\tB\"\n\013c" +
      "om.road.pbB\023PrivateChatMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_road_proto_PrivateChatMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_road_proto_PrivateChatMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_road_proto_PrivateChatMsg_descriptor,
              new java.lang.String[] { "SendId", "RecvId", "Message", },
              com.road.pb.PrivateChatMsgProto.PrivateChatMsg.class,
              com.road.pb.PrivateChatMsgProto.PrivateChatMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
