package com.road.pb;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: proto/PublicChatMessage.proto


public final class PublicChatMsgProto {
private PublicChatMsgProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
public interface PublicChatMsgOrBuilder
   extends com.google.protobuf.MessageOrBuilder {
 
 // optional bytes type = 1;
 boolean hasType();
 com.google.protobuf.ByteString getType();
 
 // optional bytes channel = 2;
 boolean hasChannel();
 com.google.protobuf.ByteString getChannel();
}
public static final class PublicChatMsg extends
   com.google.protobuf.GeneratedMessage
   implements PublicChatMsgOrBuilder {
 // Use PublicChatMsg.newBuilder() to construct.
 private PublicChatMsg(Builder builder) {
   super(builder);
 }
 private PublicChatMsg(boolean noInit) {}
 
 private static final PublicChatMsg defaultInstance;
 public static PublicChatMsg getDefaultInstance() {
   return defaultInstance;
 }
 
 public PublicChatMsg getDefaultInstanceForType() {
   return defaultInstance;
 }
 
 public static final com.google.protobuf.Descriptors.Descriptor
     getDescriptor() {
   return com.road.pb.PublicChatMsgProto.internal_static_com_road_proto_PublicChatMsg_descriptor;
 }
 
 protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
     internalGetFieldAccessorTable() {
   return com.road.pb.PublicChatMsgProto.internal_static_com_road_proto_PublicChatMsg_fieldAccessorTable;
 }
 
 private int bitField0_;
 // optional bytes type = 1;
 public static final int TYPE_FIELD_NUMBER = 1;
 private com.google.protobuf.ByteString type_;
 public boolean hasType() {
   return ((bitField0_ & 0x00000001) == 0x00000001);
 }
 public com.google.protobuf.ByteString getType() {
   return type_;
 }
 
 // optional bytes channel = 2;
 public static final int CHANNEL_FIELD_NUMBER = 2;
 private com.google.protobuf.ByteString channel_;
 public boolean hasChannel() {
   return ((bitField0_ & 0x00000002) == 0x00000002);
 }
 public com.google.protobuf.ByteString getChannel() {
   return channel_;
 }
 
 private void initFields() {
   type_ = com.google.protobuf.ByteString.EMPTY;
   channel_ = com.google.protobuf.ByteString.EMPTY;
 }
 private byte memoizedIsInitialized = -1;
 public final boolean isInitialized() {
   byte isInitialized = memoizedIsInitialized;
   if (isInitialized != -1) return isInitialized == 1;
   
   memoizedIsInitialized = 1;
   return true;
 }
 
 public void writeTo(com.google.protobuf.CodedOutputStream output)
                     throws java.io.IOException {
   getSerializedSize();
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     output.writeBytes(1, type_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     output.writeBytes(2, channel_);
   }
   getUnknownFields().writeTo(output);
 }
 
 private int memoizedSerializedSize = -1;
 public int getSerializedSize() {
   int size = memoizedSerializedSize;
   if (size != -1) return size;
 
   size = 0;
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     size += com.google.protobuf.CodedOutputStream
       .computeBytesSize(1, type_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     size += com.google.protobuf.CodedOutputStream
       .computeBytesSize(2, channel_);
   }
   size += getUnknownFields().getSerializedSize();
   memoizedSerializedSize = size;
   return size;
 }
 
 private static final long serialVersionUID = 0L;
 @java.lang.Override
 protected java.lang.Object writeReplace()
     throws java.io.ObjectStreamException {
   return super.writeReplace();
 }
 
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseFrom(
     com.google.protobuf.ByteString data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return newBuilder().mergeFrom(data).buildParsed();
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseFrom(
     com.google.protobuf.ByteString data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return newBuilder().mergeFrom(data, extensionRegistry)
            .buildParsed();
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseFrom(byte[] data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return newBuilder().mergeFrom(data).buildParsed();
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseFrom(
     byte[] data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return newBuilder().mergeFrom(data, extensionRegistry)
            .buildParsed();
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseFrom(java.io.InputStream input)
     throws java.io.IOException {
   return newBuilder().mergeFrom(input).buildParsed();
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return newBuilder().mergeFrom(input, extensionRegistry)
            .buildParsed();
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseDelimitedFrom(java.io.InputStream input)
     throws java.io.IOException {
   Builder builder = newBuilder();
   if (builder.mergeDelimitedFrom(input)) {
     return builder.buildParsed();
   } else {
     return null;
   }
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseDelimitedFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   Builder builder = newBuilder();
   if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
     return builder.buildParsed();
   } else {
     return null;
   }
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseFrom(
     com.google.protobuf.CodedInputStream input)
     throws java.io.IOException {
   return newBuilder().mergeFrom(input).buildParsed();
 }
 public static com.road.pb.PublicChatMsgProto.PublicChatMsg parseFrom(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return newBuilder().mergeFrom(input, extensionRegistry)
            .buildParsed();
 }
 
 public static Builder newBuilder() { return Builder.create(); }
 public Builder newBuilderForType() { return newBuilder(); }
 public static Builder newBuilder(com.road.pb.PublicChatMsgProto.PublicChatMsg prototype) {
   return newBuilder().mergeFrom(prototype);
 }
 public Builder toBuilder() { return newBuilder(this); }
 
 @java.lang.Override
 protected Builder newBuilderForType(
     com.google.protobuf.GeneratedMessage.BuilderParent parent) {
   Builder builder = new Builder(parent);
   return builder;
 }
 public static final class Builder extends
     com.google.protobuf.GeneratedMessage.Builder<Builder>
    implements com.road.pb.PublicChatMsgProto.PublicChatMsgOrBuilder {
   public static final com.google.protobuf.Descriptors.Descriptor
       getDescriptor() {
     return com.road.pb.PublicChatMsgProto.internal_static_com_road_proto_PublicChatMsg_descriptor;
   }
   
   protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
       internalGetFieldAccessorTable() {
     return com.road.pb.PublicChatMsgProto.internal_static_com_road_proto_PublicChatMsg_fieldAccessorTable;
   }
   
   // Construct using com.road.pb.PublicChatMsgProto.PublicChatMsg.newBuilder()
   private Builder() {
     maybeForceBuilderInitialization();
   }
   
   private Builder(BuilderParent parent) {
     super(parent);
     maybeForceBuilderInitialization();
   }
   private void maybeForceBuilderInitialization() {
     if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
     }
   }
   private static Builder create() {
     return new Builder();
   }
   
   public Builder clear() {
     super.clear();
     type_ = com.google.protobuf.ByteString.EMPTY;
     bitField0_ = (bitField0_ & ~0x00000001);
     channel_ = com.google.protobuf.ByteString.EMPTY;
     bitField0_ = (bitField0_ & ~0x00000002);
     return this;
   }
   
   public Builder clone() {
     return create().mergeFrom(buildPartial());
   }
   
   public com.google.protobuf.Descriptors.Descriptor
       getDescriptorForType() {
     return com.road.pb.PublicChatMsgProto.PublicChatMsg.getDescriptor();
   }
   
   public com.road.pb.PublicChatMsgProto.PublicChatMsg getDefaultInstanceForType() {
     return com.road.pb.PublicChatMsgProto.PublicChatMsg.getDefaultInstance();
   }
   
   public com.road.pb.PublicChatMsgProto.PublicChatMsg build() {
     com.road.pb.PublicChatMsgProto.PublicChatMsg result = buildPartial();
     if (!result.isInitialized()) {
       throw newUninitializedMessageException(result);
     }
     return result;
   }
   
   private com.road.pb.PublicChatMsgProto.PublicChatMsg buildParsed()
       throws com.google.protobuf.InvalidProtocolBufferException {
     com.road.pb.PublicChatMsgProto.PublicChatMsg result = buildPartial();
     if (!result.isInitialized()) {
       throw newUninitializedMessageException(
         result).asInvalidProtocolBufferException();
     }
     return result;
   }
   
   public com.road.pb.PublicChatMsgProto.PublicChatMsg buildPartial() {
     com.road.pb.PublicChatMsgProto.PublicChatMsg result = new com.road.pb.PublicChatMsgProto.PublicChatMsg(this);
     int from_bitField0_ = bitField0_;
     int to_bitField0_ = 0;
     if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
       to_bitField0_ |= 0x00000001;
     }
     result.type_ = type_;
     if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
       to_bitField0_ |= 0x00000002;
     }
     result.channel_ = channel_;
     result.bitField0_ = to_bitField0_;
     onBuilt();
     return result;
   }
   
   public Builder mergeFrom(com.google.protobuf.Message other) {
     if (other instanceof com.road.pb.PublicChatMsgProto.PublicChatMsg) {
       return mergeFrom((com.road.pb.PublicChatMsgProto.PublicChatMsg)other);
     } else {
       super.mergeFrom(other);
       return this;
     }
   }
   
   public Builder mergeFrom(com.road.pb.PublicChatMsgProto.PublicChatMsg other) {
     if (other == com.road.pb.PublicChatMsgProto.PublicChatMsg.getDefaultInstance()) return this;
     if (other.hasType()) {
       setType(other.getType());
     }
     if (other.hasChannel()) {
       setChannel(other.getChannel());
     }
     this.mergeUnknownFields(other.getUnknownFields());
     return this;
   }
   
   public final boolean isInitialized() {
     return true;
   }
   
   public Builder mergeFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     com.google.protobuf.UnknownFieldSet.Builder unknownFields =
       com.google.protobuf.UnknownFieldSet.newBuilder(
         this.getUnknownFields());
     while (true) {
       int tag = input.readTag();
       switch (tag) {
         case 0:
           this.setUnknownFields(unknownFields.build());
           onChanged();
           return this;
         default: {
           if (!parseUnknownField(input, unknownFields,
                                  extensionRegistry, tag)) {
             this.setUnknownFields(unknownFields.build());
             onChanged();
             return this;
           }
           break;
         }
         case 10: {
           bitField0_ |= 0x00000001;
           type_ = input.readBytes();
           break;
         }
         case 18: {
           bitField0_ |= 0x00000002;
           channel_ = input.readBytes();
           break;
         }
       }
     }
   }
   
   private int bitField0_;
   
   // optional bytes type = 1;
   private com.google.protobuf.ByteString type_ = com.google.protobuf.ByteString.EMPTY;
   public boolean hasType() {
     return ((bitField0_ & 0x00000001) == 0x00000001);
   }
   public com.google.protobuf.ByteString getType() {
     return type_;
   }
   public Builder setType(com.google.protobuf.ByteString value) {
     if (value == null) {
 throw new NullPointerException();
}
bitField0_ |= 0x00000001;
     type_ = value;
     onChanged();
     return this;
   }
   public Builder clearType() {
     bitField0_ = (bitField0_ & ~0x00000001);
     type_ = getDefaultInstance().getType();
     onChanged();
     return this;
   }
   
   // optional bytes channel = 2;
   private com.google.protobuf.ByteString channel_ = com.google.protobuf.ByteString.EMPTY;
   public boolean hasChannel() {
     return ((bitField0_ & 0x00000002) == 0x00000002);
   }
   public com.google.protobuf.ByteString getChannel() {
     return channel_;
   }
   public Builder setChannel(com.google.protobuf.ByteString value) {
     if (value == null) {
 throw new NullPointerException();
}
bitField0_ |= 0x00000002;
     channel_ = value;
     onChanged();
     return this;
   }
   public Builder clearChannel() {
     bitField0_ = (bitField0_ & ~0x00000002);
     channel_ = getDefaultInstance().getChannel();
     onChanged();
     return this;
   }
   
   // @@protoc_insertion_point(builder_scope:com.road.proto.PublicChatMsg)
 }
 
 static {
   defaultInstance = new PublicChatMsg(true);
   defaultInstance.initFields();
 }
 
 // @@protoc_insertion_point(class_scope:com.road.proto.PublicChatMsg)
}

private static com.google.protobuf.Descriptors.Descriptor
 internal_static_com_road_proto_PublicChatMsg_descriptor;
private static
 com.google.protobuf.GeneratedMessage.FieldAccessorTable
   internal_static_com_road_proto_PublicChatMsg_fieldAccessorTable;

public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\035proto/PublicChatMessage.proto\022\016com.roa" +
   "d.proto\".\n\rPublicChatMsg\022\014\n\004type\030\001 \001(\014\022\017" +
   "\n\007channel\030\002 \001(\014B!\n\013com.road.pbB\022PublicCh" +
   "atMsgProto"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
   new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
     public com.google.protobuf.ExtensionRegistry assignDescriptors(
         com.google.protobuf.Descriptors.FileDescriptor root) {
       descriptor = root;
       internal_static_com_road_proto_PublicChatMsg_descriptor =
         getDescriptor().getMessageTypes().get(0);
       internal_static_com_road_proto_PublicChatMsg_fieldAccessorTable = new
         com.google.protobuf.GeneratedMessage.FieldAccessorTable(
           internal_static_com_road_proto_PublicChatMsg_descriptor,
           new java.lang.String[] { "Type", "Channel", },
           com.road.pb.PublicChatMsgProto.PublicChatMsg.class,
           com.road.pb.PublicChatMsgProto.PublicChatMsg.Builder.class);
       return null;
     }
   };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
}

// @@protoc_insertion_point(outer_class_scope)
}
