// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BagUpdate.proto

package com.road.dota.pb;

public final class BagUpdateMsgProto {
  private BagUpdateMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BagUpdateMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.road.dota.pb.proto.UpdateMsg updateMsg = 1;
    java.util.List<com.road.dota.pb.BagUpdateMsgProto.UpdateMsg> 
        getUpdateMsgList();
    com.road.dota.pb.BagUpdateMsgProto.UpdateMsg getUpdateMsg(int index);
    int getUpdateMsgCount();
    java.util.List<? extends com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder> 
        getUpdateMsgOrBuilderList();
    com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder getUpdateMsgOrBuilder(
        int index);
  }
  public static final class BagUpdateMsg extends
      com.google.protobuf.GeneratedMessage
      implements BagUpdateMsgOrBuilder {
    // Use BagUpdateMsg.newBuilder() to construct.
    private BagUpdateMsg(Builder builder) {
      super(builder);
    }
    private BagUpdateMsg(boolean noInit) {}
    
    private static final BagUpdateMsg defaultInstance;
    public static BagUpdateMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public BagUpdateMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_BagUpdateMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_BagUpdateMsg_fieldAccessorTable;
    }
    
    // repeated .com.road.dota.pb.proto.UpdateMsg updateMsg = 1;
    public static final int UPDATEMSG_FIELD_NUMBER = 1;
    private java.util.List<com.road.dota.pb.BagUpdateMsgProto.UpdateMsg> updateMsg_;
    public java.util.List<com.road.dota.pb.BagUpdateMsgProto.UpdateMsg> getUpdateMsgList() {
      return updateMsg_;
    }
    public java.util.List<? extends com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder> 
        getUpdateMsgOrBuilderList() {
      return updateMsg_;
    }
    public int getUpdateMsgCount() {
      return updateMsg_.size();
    }
    public com.road.dota.pb.BagUpdateMsgProto.UpdateMsg getUpdateMsg(int index) {
      return updateMsg_.get(index);
    }
    public com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder getUpdateMsgOrBuilder(
        int index) {
      return updateMsg_.get(index);
    }
    
    private void initFields() {
      updateMsg_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getUpdateMsgCount(); i++) {
        if (!getUpdateMsg(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < updateMsg_.size(); i++) {
        output.writeMessage(1, updateMsg_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < updateMsg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, updateMsg_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_BagUpdateMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_BagUpdateMsg_fieldAccessorTable;
      }
      
      // Construct using com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUpdateMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (updateMsgBuilder_ == null) {
          updateMsg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          updateMsgBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg.getDescriptor();
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg getDefaultInstanceForType() {
        return com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg.getDefaultInstance();
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg build() {
        com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg buildPartial() {
        com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg result = new com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg(this);
        int from_bitField0_ = bitField0_;
        if (updateMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            updateMsg_ = java.util.Collections.unmodifiableList(updateMsg_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.updateMsg_ = updateMsg_;
        } else {
          result.updateMsg_ = updateMsgBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg) {
          return mergeFrom((com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg other) {
        if (other == com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg.getDefaultInstance()) return this;
        if (updateMsgBuilder_ == null) {
          if (!other.updateMsg_.isEmpty()) {
            if (updateMsg_.isEmpty()) {
              updateMsg_ = other.updateMsg_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUpdateMsgIsMutable();
              updateMsg_.addAll(other.updateMsg_);
            }
            onChanged();
          }
        } else {
          if (!other.updateMsg_.isEmpty()) {
            if (updateMsgBuilder_.isEmpty()) {
              updateMsgBuilder_.dispose();
              updateMsgBuilder_ = null;
              updateMsg_ = other.updateMsg_;
              bitField0_ = (bitField0_ & ~0x00000001);
              updateMsgBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUpdateMsgFieldBuilder() : null;
            } else {
              updateMsgBuilder_.addAllMessages(other.updateMsg_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getUpdateMsgCount(); i++) {
          if (!getUpdateMsg(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder subBuilder = com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUpdateMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.road.dota.pb.proto.UpdateMsg updateMsg = 1;
      private java.util.List<com.road.dota.pb.BagUpdateMsgProto.UpdateMsg> updateMsg_ =
        java.util.Collections.emptyList();
      private void ensureUpdateMsgIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          updateMsg_ = new java.util.ArrayList<com.road.dota.pb.BagUpdateMsgProto.UpdateMsg>(updateMsg_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.road.dota.pb.BagUpdateMsgProto.UpdateMsg, com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder, com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder> updateMsgBuilder_;
      
      public java.util.List<com.road.dota.pb.BagUpdateMsgProto.UpdateMsg> getUpdateMsgList() {
        if (updateMsgBuilder_ == null) {
          return java.util.Collections.unmodifiableList(updateMsg_);
        } else {
          return updateMsgBuilder_.getMessageList();
        }
      }
      public int getUpdateMsgCount() {
        if (updateMsgBuilder_ == null) {
          return updateMsg_.size();
        } else {
          return updateMsgBuilder_.getCount();
        }
      }
      public com.road.dota.pb.BagUpdateMsgProto.UpdateMsg getUpdateMsg(int index) {
        if (updateMsgBuilder_ == null) {
          return updateMsg_.get(index);
        } else {
          return updateMsgBuilder_.getMessage(index);
        }
      }
      public Builder setUpdateMsg(
          int index, com.road.dota.pb.BagUpdateMsgProto.UpdateMsg value) {
        if (updateMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateMsgIsMutable();
          updateMsg_.set(index, value);
          onChanged();
        } else {
          updateMsgBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setUpdateMsg(
          int index, com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder builderForValue) {
        if (updateMsgBuilder_ == null) {
          ensureUpdateMsgIsMutable();
          updateMsg_.set(index, builderForValue.build());
          onChanged();
        } else {
          updateMsgBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addUpdateMsg(com.road.dota.pb.BagUpdateMsgProto.UpdateMsg value) {
        if (updateMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateMsgIsMutable();
          updateMsg_.add(value);
          onChanged();
        } else {
          updateMsgBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addUpdateMsg(
          int index, com.road.dota.pb.BagUpdateMsgProto.UpdateMsg value) {
        if (updateMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateMsgIsMutable();
          updateMsg_.add(index, value);
          onChanged();
        } else {
          updateMsgBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addUpdateMsg(
          com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder builderForValue) {
        if (updateMsgBuilder_ == null) {
          ensureUpdateMsgIsMutable();
          updateMsg_.add(builderForValue.build());
          onChanged();
        } else {
          updateMsgBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addUpdateMsg(
          int index, com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder builderForValue) {
        if (updateMsgBuilder_ == null) {
          ensureUpdateMsgIsMutable();
          updateMsg_.add(index, builderForValue.build());
          onChanged();
        } else {
          updateMsgBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllUpdateMsg(
          java.lang.Iterable<? extends com.road.dota.pb.BagUpdateMsgProto.UpdateMsg> values) {
        if (updateMsgBuilder_ == null) {
          ensureUpdateMsgIsMutable();
          super.addAll(values, updateMsg_);
          onChanged();
        } else {
          updateMsgBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearUpdateMsg() {
        if (updateMsgBuilder_ == null) {
          updateMsg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          updateMsgBuilder_.clear();
        }
        return this;
      }
      public Builder removeUpdateMsg(int index) {
        if (updateMsgBuilder_ == null) {
          ensureUpdateMsgIsMutable();
          updateMsg_.remove(index);
          onChanged();
        } else {
          updateMsgBuilder_.remove(index);
        }
        return this;
      }
      public com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder getUpdateMsgBuilder(
          int index) {
        return getUpdateMsgFieldBuilder().getBuilder(index);
      }
      public com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder getUpdateMsgOrBuilder(
          int index) {
        if (updateMsgBuilder_ == null) {
          return updateMsg_.get(index);  } else {
          return updateMsgBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder> 
           getUpdateMsgOrBuilderList() {
        if (updateMsgBuilder_ != null) {
          return updateMsgBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(updateMsg_);
        }
      }
      public com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder addUpdateMsgBuilder() {
        return getUpdateMsgFieldBuilder().addBuilder(
            com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.getDefaultInstance());
      }
      public com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder addUpdateMsgBuilder(
          int index) {
        return getUpdateMsgFieldBuilder().addBuilder(
            index, com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.getDefaultInstance());
      }
      public java.util.List<com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder> 
           getUpdateMsgBuilderList() {
        return getUpdateMsgFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.road.dota.pb.BagUpdateMsgProto.UpdateMsg, com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder, com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder> 
          getUpdateMsgFieldBuilder() {
        if (updateMsgBuilder_ == null) {
          updateMsgBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.road.dota.pb.BagUpdateMsgProto.UpdateMsg, com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder, com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder>(
                  updateMsg_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          updateMsg_ = null;
        }
        return updateMsgBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.road.dota.pb.proto.BagUpdateMsg)
    }
    
    static {
      defaultInstance = new BagUpdateMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.road.dota.pb.proto.BagUpdateMsg)
  }
  
  public interface UpdateMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 slot = 1;
    boolean hasSlot();
    int getSlot();
    
    // required int32 type = 2;
    boolean hasType();
    int getType();
    
    // required bool isEmpty = 3;
    boolean hasIsEmpty();
    boolean getIsEmpty();
    
    // optional .com.road.dota.pb.proto.ItemMsg itemMsg = 4;
    boolean hasItemMsg();
    com.road.dota.pb.BagUpdateMsgProto.ItemMsg getItemMsg();
    com.road.dota.pb.BagUpdateMsgProto.ItemMsgOrBuilder getItemMsgOrBuilder();
  }
  public static final class UpdateMsg extends
      com.google.protobuf.GeneratedMessage
      implements UpdateMsgOrBuilder {
    // Use UpdateMsg.newBuilder() to construct.
    private UpdateMsg(Builder builder) {
      super(builder);
    }
    private UpdateMsg(boolean noInit) {}
    
    private static final UpdateMsg defaultInstance;
    public static UpdateMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public UpdateMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_UpdateMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_UpdateMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 slot = 1;
    public static final int SLOT_FIELD_NUMBER = 1;
    private int slot_;
    public boolean hasSlot() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSlot() {
      return slot_;
    }
    
    // required int32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getType() {
      return type_;
    }
    
    // required bool isEmpty = 3;
    public static final int ISEMPTY_FIELD_NUMBER = 3;
    private boolean isEmpty_;
    public boolean hasIsEmpty() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getIsEmpty() {
      return isEmpty_;
    }
    
    // optional .com.road.dota.pb.proto.ItemMsg itemMsg = 4;
    public static final int ITEMMSG_FIELD_NUMBER = 4;
    private com.road.dota.pb.BagUpdateMsgProto.ItemMsg itemMsg_;
    public boolean hasItemMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.road.dota.pb.BagUpdateMsgProto.ItemMsg getItemMsg() {
      return itemMsg_;
    }
    public com.road.dota.pb.BagUpdateMsgProto.ItemMsgOrBuilder getItemMsgOrBuilder() {
      return itemMsg_;
    }
    
    private void initFields() {
      slot_ = 0;
      type_ = 0;
      isEmpty_ = false;
      itemMsg_ = com.road.dota.pb.BagUpdateMsgProto.ItemMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSlot()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsEmpty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasItemMsg()) {
        if (!getItemMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, slot_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isEmpty_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, itemMsg_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, slot_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isEmpty_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, itemMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.UpdateMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.road.dota.pb.BagUpdateMsgProto.UpdateMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.road.dota.pb.BagUpdateMsgProto.UpdateMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_UpdateMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_UpdateMsg_fieldAccessorTable;
      }
      
      // Construct using com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        slot_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isEmpty_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (itemMsgBuilder_ == null) {
          itemMsg_ = com.road.dota.pb.BagUpdateMsgProto.ItemMsg.getDefaultInstance();
        } else {
          itemMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.getDescriptor();
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.UpdateMsg getDefaultInstanceForType() {
        return com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.getDefaultInstance();
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.UpdateMsg build() {
        com.road.dota.pb.BagUpdateMsgProto.UpdateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.road.dota.pb.BagUpdateMsgProto.UpdateMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.road.dota.pb.BagUpdateMsgProto.UpdateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.UpdateMsg buildPartial() {
        com.road.dota.pb.BagUpdateMsgProto.UpdateMsg result = new com.road.dota.pb.BagUpdateMsgProto.UpdateMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.slot_ = slot_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isEmpty_ = isEmpty_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (itemMsgBuilder_ == null) {
          result.itemMsg_ = itemMsg_;
        } else {
          result.itemMsg_ = itemMsgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.road.dota.pb.BagUpdateMsgProto.UpdateMsg) {
          return mergeFrom((com.road.dota.pb.BagUpdateMsgProto.UpdateMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.road.dota.pb.BagUpdateMsgProto.UpdateMsg other) {
        if (other == com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.getDefaultInstance()) return this;
        if (other.hasSlot()) {
          setSlot(other.getSlot());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasIsEmpty()) {
          setIsEmpty(other.getIsEmpty());
        }
        if (other.hasItemMsg()) {
          mergeItemMsg(other.getItemMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSlot()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasIsEmpty()) {
          
          return false;
        }
        if (hasItemMsg()) {
          if (!getItemMsg().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              slot_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isEmpty_ = input.readBool();
              break;
            }
            case 34: {
              com.road.dota.pb.BagUpdateMsgProto.ItemMsg.Builder subBuilder = com.road.dota.pb.BagUpdateMsgProto.ItemMsg.newBuilder();
              if (hasItemMsg()) {
                subBuilder.mergeFrom(getItemMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setItemMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 slot = 1;
      private int slot_ ;
      public boolean hasSlot() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSlot() {
        return slot_;
      }
      public Builder setSlot(int value) {
        bitField0_ |= 0x00000001;
        slot_ = value;
        onChanged();
        return this;
      }
      public Builder clearSlot() {
        bitField0_ = (bitField0_ & ~0x00000001);
        slot_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 type = 2;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // required bool isEmpty = 3;
      private boolean isEmpty_ ;
      public boolean hasIsEmpty() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getIsEmpty() {
        return isEmpty_;
      }
      public Builder setIsEmpty(boolean value) {
        bitField0_ |= 0x00000004;
        isEmpty_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsEmpty() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isEmpty_ = false;
        onChanged();
        return this;
      }
      
      // optional .com.road.dota.pb.proto.ItemMsg itemMsg = 4;
      private com.road.dota.pb.BagUpdateMsgProto.ItemMsg itemMsg_ = com.road.dota.pb.BagUpdateMsgProto.ItemMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.road.dota.pb.BagUpdateMsgProto.ItemMsg, com.road.dota.pb.BagUpdateMsgProto.ItemMsg.Builder, com.road.dota.pb.BagUpdateMsgProto.ItemMsgOrBuilder> itemMsgBuilder_;
      public boolean hasItemMsg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.road.dota.pb.BagUpdateMsgProto.ItemMsg getItemMsg() {
        if (itemMsgBuilder_ == null) {
          return itemMsg_;
        } else {
          return itemMsgBuilder_.getMessage();
        }
      }
      public Builder setItemMsg(com.road.dota.pb.BagUpdateMsgProto.ItemMsg value) {
        if (itemMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          itemMsg_ = value;
          onChanged();
        } else {
          itemMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setItemMsg(
          com.road.dota.pb.BagUpdateMsgProto.ItemMsg.Builder builderForValue) {
        if (itemMsgBuilder_ == null) {
          itemMsg_ = builderForValue.build();
          onChanged();
        } else {
          itemMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeItemMsg(com.road.dota.pb.BagUpdateMsgProto.ItemMsg value) {
        if (itemMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              itemMsg_ != com.road.dota.pb.BagUpdateMsgProto.ItemMsg.getDefaultInstance()) {
            itemMsg_ =
              com.road.dota.pb.BagUpdateMsgProto.ItemMsg.newBuilder(itemMsg_).mergeFrom(value).buildPartial();
          } else {
            itemMsg_ = value;
          }
          onChanged();
        } else {
          itemMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearItemMsg() {
        if (itemMsgBuilder_ == null) {
          itemMsg_ = com.road.dota.pb.BagUpdateMsgProto.ItemMsg.getDefaultInstance();
          onChanged();
        } else {
          itemMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public com.road.dota.pb.BagUpdateMsgProto.ItemMsg.Builder getItemMsgBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getItemMsgFieldBuilder().getBuilder();
      }
      public com.road.dota.pb.BagUpdateMsgProto.ItemMsgOrBuilder getItemMsgOrBuilder() {
        if (itemMsgBuilder_ != null) {
          return itemMsgBuilder_.getMessageOrBuilder();
        } else {
          return itemMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.road.dota.pb.BagUpdateMsgProto.ItemMsg, com.road.dota.pb.BagUpdateMsgProto.ItemMsg.Builder, com.road.dota.pb.BagUpdateMsgProto.ItemMsgOrBuilder> 
          getItemMsgFieldBuilder() {
        if (itemMsgBuilder_ == null) {
          itemMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.road.dota.pb.BagUpdateMsgProto.ItemMsg, com.road.dota.pb.BagUpdateMsgProto.ItemMsg.Builder, com.road.dota.pb.BagUpdateMsgProto.ItemMsgOrBuilder>(
                  itemMsg_,
                  getParentForChildren(),
                  isClean());
          itemMsg_ = null;
        }
        return itemMsgBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.road.dota.pb.proto.UpdateMsg)
    }
    
    static {
      defaultInstance = new UpdateMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.road.dota.pb.proto.UpdateMsg)
  }
  
  public interface ItemMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 count = 1;
    boolean hasCount();
    int getCount();
    
    // optional bool isNew = 2;
    boolean hasIsNew();
    boolean getIsNew();
    
    // required int32 beanId = 3;
    boolean hasBeanId();
    int getBeanId();
    
    // required bool isBind = 4;
    boolean hasIsBind();
    boolean getIsBind();
  }
  public static final class ItemMsg extends
      com.google.protobuf.GeneratedMessage
      implements ItemMsgOrBuilder {
    // Use ItemMsg.newBuilder() to construct.
    private ItemMsg(Builder builder) {
      super(builder);
    }
    private ItemMsg(boolean noInit) {}
    
    private static final ItemMsg defaultInstance;
    public static ItemMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public ItemMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_ItemMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_ItemMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 count = 1;
    public static final int COUNT_FIELD_NUMBER = 1;
    private int count_;
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCount() {
      return count_;
    }
    
    // optional bool isNew = 2;
    public static final int ISNEW_FIELD_NUMBER = 2;
    private boolean isNew_;
    public boolean hasIsNew() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsNew() {
      return isNew_;
    }
    
    // required int32 beanId = 3;
    public static final int BEANID_FIELD_NUMBER = 3;
    private int beanId_;
    public boolean hasBeanId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getBeanId() {
      return beanId_;
    }
    
    // required bool isBind = 4;
    public static final int ISBIND_FIELD_NUMBER = 4;
    private boolean isBind_;
    public boolean hasIsBind() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getIsBind() {
      return isBind_;
    }
    
    private void initFields() {
      count_ = 0;
      isNew_ = false;
      beanId_ = 0;
      isBind_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBeanId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsBind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isNew_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, beanId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isBind_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isNew_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, beanId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isBind_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.dota.pb.BagUpdateMsgProto.ItemMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.road.dota.pb.BagUpdateMsgProto.ItemMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.road.dota.pb.BagUpdateMsgProto.ItemMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_ItemMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.road.dota.pb.BagUpdateMsgProto.internal_static_com_road_dota_pb_proto_ItemMsg_fieldAccessorTable;
      }
      
      // Construct using com.road.dota.pb.BagUpdateMsgProto.ItemMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isNew_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        beanId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        isBind_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.road.dota.pb.BagUpdateMsgProto.ItemMsg.getDescriptor();
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.ItemMsg getDefaultInstanceForType() {
        return com.road.dota.pb.BagUpdateMsgProto.ItemMsg.getDefaultInstance();
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.ItemMsg build() {
        com.road.dota.pb.BagUpdateMsgProto.ItemMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.road.dota.pb.BagUpdateMsgProto.ItemMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.road.dota.pb.BagUpdateMsgProto.ItemMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.road.dota.pb.BagUpdateMsgProto.ItemMsg buildPartial() {
        com.road.dota.pb.BagUpdateMsgProto.ItemMsg result = new com.road.dota.pb.BagUpdateMsgProto.ItemMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isNew_ = isNew_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.beanId_ = beanId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isBind_ = isBind_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.road.dota.pb.BagUpdateMsgProto.ItemMsg) {
          return mergeFrom((com.road.dota.pb.BagUpdateMsgProto.ItemMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.road.dota.pb.BagUpdateMsgProto.ItemMsg other) {
        if (other == com.road.dota.pb.BagUpdateMsgProto.ItemMsg.getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasIsNew()) {
          setIsNew(other.getIsNew());
        }
        if (other.hasBeanId()) {
          setBeanId(other.getBeanId());
        }
        if (other.hasIsBind()) {
          setIsBind(other.getIsBind());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCount()) {
          
          return false;
        }
        if (!hasBeanId()) {
          
          return false;
        }
        if (!hasIsBind()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              count_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isNew_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              beanId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isBind_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 count = 1;
      private int count_ ;
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCount() {
        return count_;
      }
      public Builder setCount(int value) {
        bitField0_ |= 0x00000001;
        count_ = value;
        onChanged();
        return this;
      }
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool isNew = 2;
      private boolean isNew_ ;
      public boolean hasIsNew() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsNew() {
        return isNew_;
      }
      public Builder setIsNew(boolean value) {
        bitField0_ |= 0x00000002;
        isNew_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsNew() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isNew_ = false;
        onChanged();
        return this;
      }
      
      // required int32 beanId = 3;
      private int beanId_ ;
      public boolean hasBeanId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getBeanId() {
        return beanId_;
      }
      public Builder setBeanId(int value) {
        bitField0_ |= 0x00000004;
        beanId_ = value;
        onChanged();
        return this;
      }
      public Builder clearBeanId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        beanId_ = 0;
        onChanged();
        return this;
      }
      
      // required bool isBind = 4;
      private boolean isBind_ ;
      public boolean hasIsBind() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getIsBind() {
        return isBind_;
      }
      public Builder setIsBind(boolean value) {
        bitField0_ |= 0x00000008;
        isBind_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsBind() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isBind_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.road.dota.pb.proto.ItemMsg)
    }
    
    static {
      defaultInstance = new ItemMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.road.dota.pb.proto.ItemMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_road_dota_pb_proto_BagUpdateMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_road_dota_pb_proto_BagUpdateMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_road_dota_pb_proto_UpdateMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_road_dota_pb_proto_UpdateMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_road_dota_pb_proto_ItemMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_road_dota_pb_proto_ItemMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017BagUpdate.proto\022\026com.road.dota.pb.prot" +
      "o\"D\n\014BagUpdateMsg\0224\n\tupdateMsg\030\001 \003(\0132!.c" +
      "om.road.dota.pb.proto.UpdateMsg\"j\n\tUpdat" +
      "eMsg\022\014\n\004slot\030\001 \002(\005\022\014\n\004type\030\002 \002(\005\022\017\n\007isEm" +
      "pty\030\003 \002(\010\0220\n\007itemMsg\030\004 \001(\0132\037.com.road.do" +
      "ta.pb.proto.ItemMsg\"G\n\007ItemMsg\022\r\n\005count\030" +
      "\001 \002(\005\022\r\n\005isNew\030\002 \001(\010\022\016\n\006beanId\030\003 \002(\005\022\016\n\006" +
      "isBind\030\004 \002(\010B%\n\020com.road.dota.pbB\021BagUpd" +
      "ateMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_road_dota_pb_proto_BagUpdateMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_road_dota_pb_proto_BagUpdateMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_road_dota_pb_proto_BagUpdateMsg_descriptor,
              new java.lang.String[] { "UpdateMsg", },
              com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg.class,
              com.road.dota.pb.BagUpdateMsgProto.BagUpdateMsg.Builder.class);
          internal_static_com_road_dota_pb_proto_UpdateMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_road_dota_pb_proto_UpdateMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_road_dota_pb_proto_UpdateMsg_descriptor,
              new java.lang.String[] { "Slot", "Type", "IsEmpty", "ItemMsg", },
              com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.class,
              com.road.dota.pb.BagUpdateMsgProto.UpdateMsg.Builder.class);
          internal_static_com_road_dota_pb_proto_ItemMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_road_dota_pb_proto_ItemMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_road_dota_pb_proto_ItemMsg_descriptor,
              new java.lang.String[] { "Count", "IsNew", "BeanId", "IsBind", },
              com.road.dota.pb.BagUpdateMsgProto.ItemMsg.class,
              com.road.dota.pb.BagUpdateMsgProto.ItemMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
