// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginReq.proto

package com.road.dota.pb;

public final class LoginReqMsgProto {
  private LoginReqMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginReqMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 player_id = 1;
    boolean hasPlayerId();
    int getPlayerId();
    
    // optional string key = 2;
    boolean hasKey();
    String getKey();
    
    // repeated int32 ekeys = 3;
    java.util.List<java.lang.Integer> getEkeysList();
    int getEkeysCount();
    int getEkeys(int index);
  }
  public static final class LoginReqMsg extends
      com.google.protobuf.GeneratedMessage
      implements LoginReqMsgOrBuilder {
    // Use LoginReqMsg.newBuilder() to construct.
    private LoginReqMsg(Builder builder) {
      super(builder);
    }
    private LoginReqMsg(boolean noInit) {}
    
    private static final LoginReqMsg defaultInstance;
    public static LoginReqMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginReqMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.road.dota.pb.LoginReqMsgProto.internal_static_com_road_dota_pb_proto_LoginReqMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.road.dota.pb.LoginReqMsgProto.internal_static_com_road_dota_pb_proto_LoginReqMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 player_id = 1;
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPlayerId() {
      return playerId_;
    }
    
    // optional string key = 2;
    public static final int KEY_FIELD_NUMBER = 2;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated int32 ekeys = 3;
    public static final int EKEYS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> ekeys_;
    public java.util.List<java.lang.Integer>
        getEkeysList() {
      return ekeys_;
    }
    public int getEkeysCount() {
      return ekeys_.size();
    }
    public int getEkeys(int index) {
      return ekeys_.get(index);
    }
    
    private void initFields() {
      playerId_ = 0;
      key_ = "";
      ekeys_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getKeyBytes());
      }
      for (int i = 0; i < ekeys_.size(); i++) {
        output.writeInt32(3, ekeys_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getKeyBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < ekeys_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(ekeys_.get(i));
        }
        size += dataSize;
        size += 1 * getEkeysList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.road.dota.pb.LoginReqMsgProto.LoginReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.road.dota.pb.LoginReqMsgProto.LoginReqMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.road.dota.pb.LoginReqMsgProto.LoginReqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.road.dota.pb.LoginReqMsgProto.internal_static_com_road_dota_pb_proto_LoginReqMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.road.dota.pb.LoginReqMsgProto.internal_static_com_road_dota_pb_proto_LoginReqMsg_fieldAccessorTable;
      }
      
      // Construct using com.road.dota.pb.LoginReqMsgProto.LoginReqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ekeys_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.road.dota.pb.LoginReqMsgProto.LoginReqMsg.getDescriptor();
      }
      
      public com.road.dota.pb.LoginReqMsgProto.LoginReqMsg getDefaultInstanceForType() {
        return com.road.dota.pb.LoginReqMsgProto.LoginReqMsg.getDefaultInstance();
      }
      
      public com.road.dota.pb.LoginReqMsgProto.LoginReqMsg build() {
        com.road.dota.pb.LoginReqMsgProto.LoginReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.road.dota.pb.LoginReqMsgProto.LoginReqMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.road.dota.pb.LoginReqMsgProto.LoginReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.road.dota.pb.LoginReqMsgProto.LoginReqMsg buildPartial() {
        com.road.dota.pb.LoginReqMsgProto.LoginReqMsg result = new com.road.dota.pb.LoginReqMsgProto.LoginReqMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.key_ = key_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          ekeys_ = java.util.Collections.unmodifiableList(ekeys_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.ekeys_ = ekeys_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.road.dota.pb.LoginReqMsgProto.LoginReqMsg) {
          return mergeFrom((com.road.dota.pb.LoginReqMsgProto.LoginReqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.road.dota.pb.LoginReqMsgProto.LoginReqMsg other) {
        if (other == com.road.dota.pb.LoginReqMsgProto.LoginReqMsg.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (!other.ekeys_.isEmpty()) {
          if (ekeys_.isEmpty()) {
            ekeys_ = other.ekeys_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureEkeysIsMutable();
            ekeys_.addAll(other.ekeys_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              key_ = input.readBytes();
              break;
            }
            case 24: {
              ensureEkeysIsMutable();
              ekeys_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addEkeys(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 player_id = 1;
      private int playerId_ ;
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPlayerId() {
        return playerId_;
      }
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string key = 2;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
      }
      
      // repeated int32 ekeys = 3;
      private java.util.List<java.lang.Integer> ekeys_ = java.util.Collections.emptyList();;
      private void ensureEkeysIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          ekeys_ = new java.util.ArrayList<java.lang.Integer>(ekeys_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<java.lang.Integer>
          getEkeysList() {
        return java.util.Collections.unmodifiableList(ekeys_);
      }
      public int getEkeysCount() {
        return ekeys_.size();
      }
      public int getEkeys(int index) {
        return ekeys_.get(index);
      }
      public Builder setEkeys(
          int index, int value) {
        ensureEkeysIsMutable();
        ekeys_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addEkeys(int value) {
        ensureEkeysIsMutable();
        ekeys_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllEkeys(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureEkeysIsMutable();
        super.addAll(values, ekeys_);
        onChanged();
        return this;
      }
      public Builder clearEkeys() {
        ekeys_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.road.dota.pb.proto.LoginReqMsg)
    }
    
    static {
      defaultInstance = new LoginReqMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.road.dota.pb.proto.LoginReqMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_road_dota_pb_proto_LoginReqMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_road_dota_pb_proto_LoginReqMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016LoginReq.proto\022\026com.road.dota.pb.proto" +
      "\"<\n\013LoginReqMsg\022\021\n\tplayer_id\030\001 \001(\005\022\013\n\003ke" +
      "y\030\002 \001(\t\022\r\n\005ekeys\030\003 \003(\005B$\n\020com.road.dota." +
      "pbB\020LoginReqMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_road_dota_pb_proto_LoginReqMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_road_dota_pb_proto_LoginReqMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_road_dota_pb_proto_LoginReqMsg_descriptor,
              new java.lang.String[] { "PlayerId", "Key", "Ekeys", },
              com.road.dota.pb.LoginReqMsgProto.LoginReqMsg.class,
              com.road.dota.pb.LoginReqMsgProto.LoginReqMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
